name: Arcade
run-name: Mirroring to main 

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2028/B-OOP-400-PAR-4-1-arcade-luigi.gomes.git'
  EXECUTABLES: 'arcade'

jobs:
  is_mirror:
    runs-on: ubuntu-latest
    if: github.repository != 'EpitechPromo2028/B-OOP-400-PAR-4-1-arcade-luigi.gomes'
    steps:
      - run: ls

  push_to_mirror:
    needs: [is_mirror]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}